/**
 * SpotFinder IT Del - Database Spot Belajar Kampus Institut Teknologi Del (Laguboti)
 */

const IT_DEL_SPOTS = [
    {
        id: "spot-gazebo-danau",
        name: "Gazebo View Danau Toba (Taman Del)",
        category: "outdoor",
        building: "Area Taman Tepian Danau IT Del",
        floor: "Outdoor / Taman Terbuka",
        campusZone: "Tepi Danau Toba",
        distance: "90 m dari Perpus",
        availableSeats: 12,
        totalCapacity: 20,
        status: "available",
        noiseLevel: "Tenang & Angin Segar 🍃",
        noiseScore: 1,
        wifiSpeed: "85 Mbps (Del-Outdoor) 📶",
        ac: false,
        powerOutlets: true,
        whiteboard: false,
        outdoor: true,
        rating: 4.9,
        openHours: "06:00 - 18:30 WIB",
        description: "Spot belajar outdoor asri dengan pemandangan langsung Danau Toba dan perbukitan Sitoluama. Tersedia stopkontak di tiang gazebo.",
        imageIcon: "🏞️",
        tags: ["View Danau Toba", "Outdoor Sejuk", "Angin Segar", "Ada Stopkontak"],
        peakHours: "15:30 - 17:30 WIB",
        seats: [
            { id: "GZ1", status: "occupied", user: "Mahasiswa Informatika" },
            { id: "GZ2", status: "occupied", user: "Mahasiswa Sistem Informasi" },
            { id: "GZ3", status: "occupied", user: "Mahasiswa Elektro" },
            { id: "GZ4", status: "occupied", user: "Mahasiswa Bioproses" },
            { id: "GZ5", status: "occupied", user: "Mahasiswa Manajemen Rekayasa" },
            { id: "GZ6", status: "occupied", user: "Mahasiswa Informatika" },
            { id: "GZ7", status: "occupied", user: "Mahasiswa Vokasi TI" },
            { id: "GZ8", status: "occupied", user: "Mahasiswa Vokasi TK" },
            { id: "GZ9", status: "available" },
            { id: "GZ10", status: "available" },
            { id: "GZ11", status: "available" },
            { id: "GZ12", status: "available" },
            { id: "GZ13", status: "available" },
            { id: "GZ14", status: "available" },
            { id: "GZ15", status: "available" },
            { id: "GZ16", status: "available" },
            { id: "GZ17", status: "available" },
            { id: "GZ18", status: "available" },
            { id: "GZ19", status: "available" },
            { id: "GZ20", status: "available" }
        ]
    },
    {
        id: "spot-perpus-itdel",
        name: "Perpustakaan IT Del (Lantai 2)",
        category: "library",
        building: "Gedung Perpustakaan & Lab IT Del",
        floor: "Lantai 2 - Zona Hening & Mandiri",
        campusZone: "Zona Akademik Tengah",
        distance: "40 m dari GD 5",
        availableSeats: 8,
        totalCapacity: 45,
        status: "available",
        noiseLevel: "Sangat Hening (Zona Skripsi) 🤫",
        noiseScore: 1,
        wifiSpeed: "190 Mbps (Del-Student) ⚡",
        ac: true,
        powerOutlets: true,
        whiteboard: false,
        outdoor: false,
        rating: 4.95,
        openHours: "08:00 - 21:30 WIB",
        description: "Perpustakaan pusat Institut Teknologi Del. Suasana sangat kondusif untuk membaca, mengerjakan tugas akhir/skripsi, dan belajar mandiri dengan colokan di setiap partisi meja.",
        imageIcon: "📚",
        tags: ["Perpus IT Del", "Hening", "Colokan Tiap Meja", "Wi-Fi Del-Student", "AC Dingin"],
        peakHours: "13:00 - 16:30 WIB",
        seats: [
            { id: "P1", status: "occupied", user: "Mahasiswa IF '23" },
            { id: "P2", status: "occupied", user: "Mahasiswa SI '22" },
            { id: "P3", status: "available" },
            { id: "P4", status: "available" },
            { id: "P5", status: "occupied", user: "Mahasiswa TE '21" },
            { id: "P6", status: "available" },
            { id: "P7", status: "occupied", user: "Mahasiswa MR '24" },
            { id: "P8", status: "available" },
            { id: "P9", status: "available" },
            { id: "P10", status: "occupied", user: "Mahasiswa TRPL" },
            { id: "P11", status: "available" },
            { id: "P12", status: "available" },
            { id: "P13", status: "available" },
            { id: "P14", status: "occupied" }
        ]
    },
    {
        id: "spot-gd7-study",
        name: "Ruang Belajar Bersama (Gedung 7 - GD 712)",
        category: "study-room",
        building: "Gedung Perkuliahan GD 7",
        floor: "Lantai 1 - Ruang Diskusi",
        campusZone: "Zona Kuliah GD",
        distance: "120 m dari Asrama",
        availableSeats: 3,
        totalCapacity: 26,
        status: "almost-full",
        noiseLevel: "Diskusi & Bedah Proyek 🗣️",
        noiseScore: 2,
        wifiSpeed: "150 Mbps (Del-Student) ⚡",
        ac: true,
        powerOutlets: true,
        whiteboard: true,
        outdoor: false,
        rating: 4.8,
        openHours: "07:30 - 22:00 WIB",
        description: "Ruang belajar favorit mahasiswa Del untuk ngerjain tugas proyek kelompok (PA / TA), coding bareng, dan diskusi materi praktikum.",
        imageIcon: "💡",
        tags: ["GD 7 Del", "Ada Whiteboard", "Diskusi Proyek PA", "Colokan Banyak"],
        peakHours: "16:00 - 20:00 WIB",
        seats: [
            { id: "GD1", status: "occupied", user: "Tim Proyek PA 1" },
            { id: "GD2", status: "occupied", user: "Tim Proyek PA 1" },
            { id: "GD3", status: "occupied", user: "Tim Proyek PA 1" },
            { id: "GD4", status: "available" },
            { id: "GD5", status: "available" },
            { id: "GD6", status: "available" },
            { id: "GD7", status: "occupied", user: "Kelompok DAA" }
        ]
    },
    {
        id: "spot-lab-gd9",
        name: "Lab Komputer Terbuka (Gedung 9 - GD 921)",
        category: "lab",
        building: "Gedung 9 IT Del",
        floor: "Lantai 2 - Lab Komputasi",
        campusZone: "Zona Lab & Riset",
        distance: "60 m dari GD 7",
        availableSeats: 6,
        totalCapacity: 35,
        status: "available",
        noiseLevel: "Hening / Fokus Koding ⌨️",
        noiseScore: 1,
        wifiSpeed: "350 Mbps (Gigabit LAN & WiFi) 🚀",
        ac: true,
        powerOutlets: true,
        whiteboard: false,
        outdoor: false,
        rating: 4.95,
        openHours: "08:00 - 21:00 WIB",
        description: "Laboratorium komputer dengan koneksi gigabit super kencang. Sangat cocok untuk praktikum pemrograman, simulasi jaringan, dan pengerjaan tugas besar.",
        imageIcon: "🖥️",
        tags: ["Lab GD 9", "Koneksi Gigabit", "PC Lab Tersedia", "AC Dingin"],
        peakHours: "14:00 - 18:00 WIB",
        seats: [
            { id: "PC1", status: "occupied", user: "Mahasiswa IF '23" },
            { id: "PC2", status: "occupied", user: "Mahasiswa IF '23" },
            { id: "PC3", status: "available" },
            { id: "PC4", status: "available" },
            { id: "PC5", status: "occupied", user: "Mahasiswa TI '22" },
            { id: "PC6", status: "available" }
        ]
    },
    {
        id: "spot-sopo-del",
        name: "Sopo Del Student Lounge",
        category: "study-room",
        building: "Kompleks Sopo Del",
        floor: "Lantai 1",
        campusZone: "Pusat Kegiatan Mahasiswa",
        distance: "110 m dari Kantin",
        availableSeats: 5,
        totalCapacity: 30,
        status: "available",
        noiseLevel: "Diskusi & Santai ☕",
        noiseScore: 2,
        wifiSpeed: "130 Mbps 📶",
        ac: true,
        powerOutlets: true,
        whiteboard: true,
        outdoor: false,
        rating: 4.75,
        openHours: "08:00 - 22:00 WIB",
        description: "Area santai modern mahasiswa IT Del dengan sofa nyaman, meja bundar diskusi, dan akses stopkontak.",
        imageIcon: "🛋️",
        tags: ["Sopo Del", "Sofa Nyaman", "Diskusi Organisasi", "Stopkontak"],
        peakHours: "17:00 - 20:30 WIB",
        seats: [
            { id: "SP1", status: "occupied" },
            { id: "SP2", status: "available" },
            { id: "SP3", status: "available" },
            { id: "SP4", status: "available" },
            { id: "SP5", status: "available" },
            { id: "SP6", status: "available" }
        ]
    },
    {
        id: "spot-kantin-del",
        name: "Kantin Utama IT Del",
        category: "cafeteria",
        building: "Pusat Kantin & Cafeteria Del",
        floor: "Lantai Dasar",
        campusZone: "Zona Asrama & Layanan",
        distance: "80 m dari Lapangan",
        availableSeats: 0,
        totalCapacity: 120,
        status: "crowded",
        noiseLevel: "Ramai & Jam Makan Siang 🍽️",
        noiseScore: 3,
        wifiSpeed: "60 Mbps (Del-Guest) 📶",
        ac: false,
        powerOutlets: false,
        whiteboard: false,
        outdoor: true,
        rating: 4.5,
        openHours: "07:00 - 19:30 WIB",
        description: "Kantin kampus IT Del. Kondisi saat ini sangat ramai oleh antrean makan siang mahasiswa dan civitas akademika.",
        imageIcon: "🍱",
        tags: ["Kantin IT Del", "Makan Siang", "Ramai", "Suasana Santai"],
        peakHours: "11:45 - 13:45 WIB",
        seats: [
            { id: "K1", status: "occupied" },
            { id: "K2", status: "occupied" },
            { id: "K3", status: "occupied" },
            { id: "K4", status: "occupied" }
        ]
    }
];

const IT_DEL_LIVE_UPDATES = [
    { text: "Perpustakaan IT Del Lt. 2: Tersedia 8 tempat kosong di area meja mandiri", time: "1 mnt lalu" },
    { text: "Ruang Belajar GD 712: Sisa 3 kursi kosong untuk diskusi kelompok tugas", time: "3 mnt lalu" },
    { text: "Kantin IT Del: Antrean makan siang sedang padat (Penuh)", time: "5 mnt lalu" },
    { text: "Gazebo Danau Toba: 12 kursi kosong dengan angin sepoi-sepoi", time: "7 mnt lalu" }
];

const IT_DEL_LOST_FOUND = [
    {
        id: "lf-1",
        item: "Laptop ASUS VivoBook 14 (Warna Silver Metalik)",
        category: "laptop",
        categoryLabel: "💻 Laptop & Komputer",
        spotId: "spot-gazebo-danau",
        spotName: "Gazebo View Danau Toba",
        locationDetail: "Meja Gazebo GZ-4 dekat tiang stopkontak sebelah barat",
        timeFound: "Hari ini, 14:15 WIB",
        status: "unclaimed",
        keptAt: "Pos Satpam Gerbang Danau IT Del (Pak Simanjuntak)",
        finder: "Petugas Kebersihan Taman Del",
        icon: "💻",
        contactNote: "⚠️ Wajib verifikasi: Pemilik harus menyebutkan password login & stiker yang terpasang di cover laptop."
    },
    {
        id: "lf-2",
        item: "Smartphone iPhone 13 (Warna Midnight / Case Bening)",
        category: "smartphone",
        categoryLabel: "📱 HP & Tablet",
        spotId: "spot-perpus-itdel",
        spotName: "Perpustakaan IT Del (Lantai 2)",
        locationDetail: "Meja Partisi P-05 Area Skripsi & Jurnal",
        timeFound: "Hari ini, 12:30 WIB",
        status: "unclaimed",
        keptAt: "Meja Resepsionis / Sirkulasi Perpustakaan Lt. 1",
        finder: "Pustakawan Del (Ibu Silalahi)",
        icon: "📱",
        contactNote: "Silakan buka kunci layar (Face ID / Passcode) di depan petugas perpus untuk klaim."
    },
    {
        id: "lf-3",
        item: "Charger Laptop Type-C 65W Fast Charging (Hitam)",
        category: "elektronik",
        categoryLabel: "🔌 Charger & Aksesoris",
        spotId: "spot-gd7-study",
        spotName: "Ruang Belajar Bersama (Gedung 7)",
        locationDetail: "Di stopkontak dinding bawah whiteboard GD 712",
        timeFound: "Hari ini, 10:45 WIB",
        status: "unclaimed",
        keptAt: "Laboran Gedung 7 (Pak Sihombing)",
        finder: "Mahasiswa Sistem Informasi",
        icon: "🔌",
        contactNote: "Sebutkan merk adaptor dan panjang kabel saat mengambil."
    },
    {
        id: "lf-4",
        item: "Dompet Kulit Cokelat + KTM Informatika 2023",
        category: "ktm",
        categoryLabel: "🪪 Dompet & KTM",
        spotId: "spot-lab-gd9",
        spotName: "Lab Komputer Terbuka (Gedung 9)",
        locationDetail: "Di samping keyboard meja PC-08 Lantai 2",
        timeFound: "Kemarin, 19:20 WIB",
        status: "unclaimed",
        keptAt: "Laboran Gedung 9 (Pak Marpaung)",
        finder: "Asisten Lab Komputasi",
        icon: "🪪",
        contactNote: "Bawa bukti NIM atau KTP untuk konfirmasi kepemilikan dompet & KTM."
    },
    {
        id: "lf-5",
        item: "Tumbler Stainless Steel IT Del Edition (Navy Blue)",
        category: "tumbler",
        categoryLabel: "🥤 Botol Minum / Tumbler",
        spotId: "spot-sopo-del",
        spotName: "Sopo Del Student Lounge",
        locationDetail: "Meja sofa santai sudut timur dekat TV",
        timeFound: "Kemarin, 16:00 WIB",
        status: "unclaimed",
        keptAt: "Pengurus Sopo Del / Student Lounge",
        finder: "Mahasiswa Vokasi TI",
        icon: "🥤",
        contactNote: "Terdapat inisial nama di bagian bawah tumbler."
    },
    {
        id: "lf-6",
        item: "Tas Ransel Laptop Eiger (Warna Abu-Abu)",
        category: "tas",
        categoryLabel: "🎒 Tas & Ransel",
        spotId: "spot-kantin-del",
        spotName: "Kantin Utama Del",
        locationDetail: "Kursi kayu panjang area luar kantin",
        timeFound: "2 hari lalu",
        status: "claimed",
        keptAt: "Sudah diserahkan kembali kepada pemilik (Mahasiswa Elektro)",
        finder: "Pengelola Kantin Utama",
        icon: "🎒",
        contactNote: "Status: Selesai Dikembalikan"
    }
];
